[versions]
protocol = "3.0.0.Beta12-20260209.180455-4"
jackson = "3.0.3"

[libraries]
bedrock-codec = { group = "org.cloudburstmc.protocol", name = "bedrock-codec", version.ref = "protocol" }
bedrock-common = { group = "org.cloudburstmc.protocol", name = "common", version.ref = "protocol" }
bedrock-connection = { group = "org.cloudburstmc.protocol", name = "bedrock-connection", version.ref = "protocol" }
common = { group = "com.nukkitx", name = "common", version = "1.0.1-SNAPSHOT" }
jackson-databind = { group = "tools.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "tools.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version = "2.4.2" }
jline-reader = { group = "org.jline", name = "jline-reader", version = "3.30.6" }
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.42" }
spotbugs-annotations = { group = "com.github.spotbugs", name = "spotbugs-annotations", version = "4.9.8" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
