[versions]
protocol = "3.0.0.Beta11-SNAPSHOT"
jackson = "2.17.2"

[libraries]
bedrock-codec = { group = "org.cloudburstmc.protocol", name = "bedrock-codec", version.ref = "protocol" }
bedrock-common = { group = "org.cloudburstmc.protocol", name = "common", version.ref = "protocol" }
bedrock-connection = { group = "org.cloudburstmc.protocol", name = "bedrock-connection", version.ref = "protocol" }
common = { group = "com.nukkitx", name = "common", version = "1.0.1-SNAPSHOT" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version = "2.4.1" }
jline-reader = { group = "org.jline", name = "jline-reader", version = "3.26.3" }
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.34" }
spotbugs-annotations = { group = "com.github.spotbugs", name = "spotbugs-annotations", version = "4.8.6" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "8.3.0" }