[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.26" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version = "3.0.2" }
bedrock-codec = { group = "org.cloudburstmc.protocol", name = "bedrock-codec", version = "3.0.0.Beta1-20230908.171156-106" }
bedrock-connection = { group = "org.cloudburstmc.protocol", name = "bedrock-connection", version = "3.0.0.Beta1-20230908.171156-105" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version = "2.14.2" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version = "2.14.2" }
common = { group = "com.nukkitx", name = "common", version = "1.0.1-SNAPSHOT" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version = "2.4.0" }
jline-reader = { group = "org.jline", name = "jline-reader", version = "3.23.0" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
