[libraries]
bedrock-codec = { group = "org.cloudburstmc.protocol", name = "bedrock-codec", version = "3.0.0.Beta1-SNAPSHOT" }
bedrock-common = { group = "org.cloudburstmc.protocol", name = "common", version = "3.0.0.Beta1-SNAPSHOT" }
bedrock-connection = { group = "org.cloudburstmc.protocol", name = "bedrock-connection", version = "3.0.0.Beta1-SNAPSHOT" }
common = { group = "com.nukkitx", name = "common", version = "1.0.1-SNAPSHOT" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version = "2.15.3" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version = "2.15.3" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version = "2.4.1" }
jline-reader = { group = "org.jline", name = "jline-reader", version = "3.24.1" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version = "3.0.2" }
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.30" }
reflections = { group = "org.reflections", name = "reflections", version = "0.10.2" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
